---
title: "sim_community"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sim_community}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(birdsize)
library(dplyr)
```

# Simulation from a BBS route

Load and preprocess data. The `new_hartford_raw` dataset is the BBS survey route for New Hartford, CT.

```{r}

new_hartford_raw <- new_hartford_raw

new_hartford_clean <- new_hartford_raw %>%
  filter_bbs_survey() %>%
  dplyr::filter(year == 1994)

head(new_hartford_clean)
```


```{r}
set.seed(22)

new_hartford_sims <- community_generate(community_data_table = new_hartford_clean)

head(new_hartford_sims)
```

# Simulation given species' names

```{r}

new_hartford_names <- new_hartford_clean %>%
  left_join(select(sd_table, aou, genus, species)) %>%
  select(-aou)

```

```{r}

set.seed(22)

new_hartford_names_sims <- community_generate(new_hartford_names)

head(new_hartford_names_sims)

```


# Simulation given mean size measurements

```{r}

new_hartford_means <- new_hartford_clean %>%
  left_join(select(sd_table, aou, mean_mass)) %>%
  select(-aou) %>%
  rename(mean_size = mean_mass)



set.seed(22)

new_hartford_means_sims <- community_generate(new_hartford_means)

head(new_hartford_means_sims)


```


# Simulation given mean size and sd measurements

```{r}

new_hartford_mean_sds <- new_hartford_clean %>%
  left_join(select(sd_table, aou, mean_mass, mean_sd)) %>%
  select(-aou) %>%
  rename(mean_size = mean_mass,
         sd_size = mean_sd)



set.seed(22)

new_hartford_mean_sds_sims <- community_generate(new_hartford_mean_sds)

head(new_hartford_mean_sds_sims)

```

# Simulation given a mix of AOUs and mean sizes

```{r}
new_hartford_mix <- bind_rows(
  new_hartford_clean[1:32,],
  new_hartford_means[33:62,]
)

head(new_hartford_mix)

set.seed(22)

new_hartford_mix_sims <- community_generate(new_hartford_mix)

head(new_hartford_mix_sims)
tail(new_hartford_mix_sims)
```
