#' Summary statistics for a population
#'
#' @param population dataframe generated by [pop_generate].
#'
#' @return dataframe of summary metrics for population
#' @export
#'
#' @examples
#' a_population <- pop_generate(10, mean_size= 20)
#' pop_summarize(a_population)
#' @importFrom dplyr group_by_at summarize ungroup n distinct
#' @importFrom stats sd
pop_summarize <- function(population) {

  summarize_vars <- c("individual_mass", "individual_bmr")

  id_vars <- colnames(population)[ which(!(colnames(population) %in% summarize_vars))]

  if(nrow(dplyr::distinct(population[,id_vars])) > 1) {
    warning("`population` data frame contains multiple id groups; population-wide summary may not work as expected!")
  }

  population %>%
    dplyr::group_by_at(id_vars) %>%
    dplyr::summarize(population_abundance = dplyr::n(),
                     population_biomass = sum(.data$individual_mass),
                     population_metabolic_rate = sum(.data$individual_bmr),
                     population_mean_size = mean(.data$individual_mass),
                     population_sd_size = sd(.data$individual_mass),
                     population_mean_bmr = mean(.data$individual_bmr),
                     population_sd_bmr = sd(.data$individual_bmr)) %>%
    dplyr::ungroup()

}

#' Compute summary statistics for a community
#'
#' @param community result of [community_generate]
#' @param level one of: "year", "species", "species_and_year", "custom"
#' @param id_vars vector of column names to group by, if using "custom" level
#'
#' @return summarized community data frame
#' @export
#'
#' @examples
#' bbs_route <- new_hartford_raw %>% filter_bbs_survey()
#' community_data <- community_generate(bbs_route)
#' community_summarize(community_data)
#'
#' @importFrom dplyr group_by_at summarize ungroup n
#' @importFrom stats sd
#'
#'
community_summarize <- function(community, level = c("year", "species", "species_and_year", "custom"), id_vars = NULL) {

  # Check community has the variables to sum over

  if(!(all(c("individual_mass", "individual_bmr") %in% colnames(community)))) {
    stop("`community` is missing columns for body size and/or metabolic rate")
  }

  # Grouping

  level = match.arg(level, several.ok = F)


  id_vars <- switch(level,
                    year = c("routedataid", "countrynum", "statenum", "route", "rpid", "year"),
                    species = c("countrynum", "statenum", "route", "rpid", "aou","sim_species_id", "genus", "species"),
                    species_and_year = c("routedataid", "countrynum", "statenum", "route", "rpid", "year", "aou", "sim_species_id", "genus", "species"),
                    custom = id_vars)

  if(level == "custom" && is.null(id_vars)) {
    stop("Set custom `id_vars` using `id_vars` argument")
  }

  id_vars <- id_vars[ which(id_vars %in% colnames(community))]

  if(length(id_vars) == 0) {
    stop("No `id_vars` present in `community`")
  }

  community <- identify_richness_designator(community)

  community %>%
    dplyr::group_by_at(c(id_vars, "species_designator")) %>%
    dplyr::summarize(
      total_abundance = dplyr::n(),
      total_biomass = sum(.data$individual_mass),
      total_metabolic_rate = sum(.data$individual_bmr),
      total_richness = length(unique(.data$richnessSpecies)),
      mean_individual_mass = mean(.data$individual_mass),
      sd_individual_mass = sd(.data$individual_mass),
      mean_metabolic_rate = mean(.data$individual_bmr),
      sd_metabolic_rate = sd(.data$individual_bmr)
    ) %>%
    dplyr::ungroup()

}


#' Identify the column to use to compute species richness
#'
#' @param community result of [community_generate]
#'
#' @return `community` having identified the best-guess column for species richness
#' @keywords internal
#'
#' @importFrom dplyr mutate
identify_richness_designator <- function(community) {

  if(!(any("aou" %in% colnames(community),
           "sim_species_id" %in% colnames(community),
           all(c("genus", "species") %in% colnames(community)),
           all(c("mean_size", "sd_size", "abundance") %in% colnames(community))))) {

    community <- community %>%
      dplyr::mutate(
        richnessSpecies = NA,
        species_designator = "none_identified"
      )

    message("No identifiable species designator to calculat species richness!")
    return(community)
  }

  if("aou" %in% colnames(community)) {
    if(!anyNA(community$aou)) {
      community <- community %>%
        dplyr::mutate(
          richnessSpecies = .data$aou,
          species_designator = "aou"
        )
      return(community)
    }
  }

  if(all(c("genus", "species") %in% colnames(community))) {
    if(!anyNA(community$genus) && !anyNA(community$species)) {
      community <- community %>%
        dplyr::mutate(
          richnessSpecies = paste0(.data$genus, .data$species),
          species_designator = "scientificName"
        )
      return(community)
    }
  }

  if("sim_species_id" %in% colnames(community)) {
    if(!anyNA(community$sim_species_id)) {
      community <- community %>%
        dplyr::mutate(
          richnessSpecies = .data$sim_species_id,
          species_designator = "sim_species_id"
        )
      return(community)
    }
  }

  community <- community %>%
    dplyr::mutate(
      richnessSpecies = paste(.data$mean_size, .data$sd_size, .data$abundance, sep = "_"),
      species_designator = "sim_parameters"
    )

  return(community)

}
